import {NgModule} from '@angular/core';
import {MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule,MatIconModule,MatToolbarModule,MatListModule,MatSidenavModule} from '@angular/material'
@NgModule({
    imports:[MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule,MatIconModule,MatToolbarModule,MatListModule,MatSidenavModule],


    exports:[MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule,MatIconModule,MatToolbarModule,MatListModule,MatSidenavModule]
})
export class Meterial{}