import {NgModule} from '@angular/core';
import {MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule} from '@angular/material'
@NgModule({
    imports:[MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule],


    exports:[MatButtonModule,MatInputModule,MatFormFieldModule,MatCheckboxModule,MatCardModule,MatTabsModule,MatRadioModule,MatDatepickerModule,MatNativeDateModule,MatSnackBarModule,MatAutocompleteModule,MatSelectModule,MatDialogModule,MatPaginatorModule,MatProgressSpinnerModule]
})
export class Meterial{}